---
- hosts: machine
  become: true
  gather_facts: true

  pre_tasks:
    - name: Print message
      debug:
        msg: Starting setup ubuntu dev machine

    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude', 'git', 'python3-pip' ]
      
    - name: Install hello apt for sample only
      apt: name=hello state=latest

    - name: Check Ansible version
      command: ansible --version
      register: ansibleVersion

    - name: Print version
      debug:
        msg: "Ansible Version: {{ ansibleVersion.stdout }}"

  roles:
    - dev-server
