- name: Install prerequisites software
  apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'software-properties-common' ]

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository ubuntu {{ ansible_distribution_release }}
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update apt and install docker-ce
  apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
  loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]

- name: Add user {{ home_user }} to group sudo docker
  user:
    name: '{{ home_user }}'
    groups: docker
    append: yes
  notify: Success Docker Install
