- name: "Set variables java version"
  set_fact:
    java_lib: '{{ java_version }}'

- name: Read jdk version for linux {{ ansible_architecture }} from file jdk{{ java_lib }}_{{ ansible_architecture }}.yml
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - 'jdk{{ java_lib }}_{{ ansible_architecture }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: Install JDK Version {{ jdk_release }}
  debug:
     msg: "installing jdk version {{ jdk_release }} {{ ansible_architecture }}"

- name: Get JDK{{ java_lib }} file for linux from {{ jdk_url }}
  get_url:
     url: "{{ jdk_url }}"
     dest: "{{ home_dir }}/open-jdk-{{ java_lib }}.tar.gz"

- name: Make java directory
  file:
     path: /usr/lib/jdk
     state: directory

- name: unpack JDK file
  unarchive:
     dest: /usr/lib/jdk
     src: "{{ home_dir }}/open-jdk-{{ java_lib }}.tar.gz"
     remote_src: yes

- name: Remove downloaded jdk file
  file:
    path: "{{ home_dir }}/open-jdk-{{ java_lib }}.tar.gz"
    state: absent

- name: update alternatives for java {{ java_lib }}
  alternatives:
     name: java
     path: '/usr/lib/jdk/{{ jdk_release }}/bin/java'
     link: /usr/bin/java
     priority: 20000

- name: install maven
  apt:
    name: maven
    update_cache: yes