# default is jdk8 amd64
jdk_url: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u322-b06/OpenJDK8U-jdk_x64_linux_hotspot_8u322b06.tar.gz
jdk_release: jdk8u322-b06

# default golang arch is amd64
golang_architecture: linux-amd64

# default minconda arch is amd64
miniconda_url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
miniconda_checksum: sha256:4ee9c3aa53329cd7a63b49877c0babb49b19b7e5af29807b793a76bdb1d362b4
